### ISSUE TITLE
Find sound effects for map

### ISSUE THREAD

**Issue by Inventor4life** [A5rocks/code-jam-10#17]
singular footstep
door opening
some form of alert sound ("like a secretary bell) when new items are picked up
one action sound (like sliding, scraping, or clicking when a puzzle piece is interacted with)

**Comment by A5rocks** [comment]
>  one action sound (like sliding, scraping, or clicking when a puzzle piece is interacted with)

I think this is a priority for basic polish. (along with having faint borders around pieces?

**Comment by Inventor4life** [comment]
Potentially on the piece borders. The only one it might matter for is the sliding puzzle, and that has somewhat distinct piece borders already
